# This has to be version .2 - BECAUSE. See: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax
version: 0.2
env:
  parameter-store:
    GITLAB_ACCESS_TOKEN: "/SAMLB/DEV/Gitlab/TOKEN"
    REPO_USER:  "/SAMLB/DEV/ARTIFACT/USER"
    REPO_PASS:  "/SAMLB/DEV/ARTIFACT/PASS"
  git-credential-helper: "yes"
phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
    commands:
      - yum install -y git
      - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
      - yum install -y yarn
      - yarn global add aws-cdk
      - export PATH="$(yarn global bin):$PATH"
  pre_build:
    commands:
      - git clone https://oauth2Service:${GITLAB_ACCESS_TOKEN}@gitlab.bpimb-era.org/DLP/daids-learning-portal.git
      - cd daids-learning-portal
      - git checkout ${BRANCH}
      - docker login platform-docker.artifactory.niaid.nih.gov --username $REPO_USER --password $REPO_PASS
  build:
    commands:
      - cd cdk
      - yarn
      - yarn run build
      - cdk deploy --verbose --require-approval never ${STACK}


